- lib/ui/toolbar.js
- package.json
For the last one, I did not test it on Windows, so hopefully the width of the menu is similar?
> Minor changes

- lib/appc.js
- lib/providers/autoCompleteHelper.js
- lib/tiapp.js
- lib/ui/toolbar.js
- lib/utils.js
[ATOM-30] Non-wildcard iOS provisioning profiles always shown as disabled
Marking managed provisioning profiles as invalid
Fixes provisioning profile ordering
[ATOM-28] Autocomplete error when creating styles for classes
> iOS provisioning profile fixes

- lib/index.js
- lib/ui/button.js
- lib/ui/console.js
- lib/ui/toolbar.js
- styles/appc.less
- Fix #91: Add expiration date to certificates **and** provisioning profiles
- Fix #108: Add LiveView
- Fix #103: Fix HUD-error
- Fix #90: Use `INFO` log-level by default, for parity with Studio
- Fix #114: Allow custom args to be saved across Atom sessions
> Some bug-fixes and improvements

- lib/project.js
Always attach the watcher, only emit modified event if parsing was successful. 
Fixes #128
Tests
1. Make your tiapp invalid (like in the linked issue), save it. A workspace error should be shown, but not other errors.
2. Fix the tiapp and the plugin should still function
3. Open a project with an invalid tiapp, it should notify that the tiapp is invalid. The watcher should still function (you can check by fixing and then re-invalidating the tiapp.
There's still an issue around opening a project where the tiapp is invalid, the build bar functionality doesn't get set up once the tiapp is fixed
> Fix error being thrown when tiapp is invalid

- lib/appc.js
- lib/index.js
Fixes #106
To test:
1. Remove/rename your sdk folder
2. Remove the completions file
3. Open a project. You should get an error that there's no SDK installed, with a button to install the latest SDK, once the SDK is installed a success message should pop up
> Check if SDK is installed before generating autocompletion file and allow a user to install an SDK if they dont have one.

- lib/index.js
- lib/menu/app.js
- lib/ui/console.jsx
- lib/ui/toolbar.jsx
- package.json
https://github.com/appcelerator/atom-appcelerator-titanium/issues/138
When set to `false` the top toolbar is hidden. Default is still `true`
> Option to hide the top toolbar

- lib/providers/styleAutoCompleteProvider.js
- spec/styleAutoCompleteProvider-spec.js
Fixes #139
1. Setup a tss like the below
2. Type in `""` should get all suggested
3. Type in `"ma"` - should get magenta and maroon suggested
3. Type in `"mage"` - should get just magenta
```
"label": {
color: 
}
```
> fix(autocomplete): correct filtering of colors

- lib/providers/definitionsProvider.js
While this works in alloy, we should try and guide people to not create tss rules by id in the app.tss
Closes #141
1. Add an id in an xml tag
2. `cmd+click` the id name
It should only offer `Generate style <name of file>`
> fix(definitions): do not suggest app.tss when generating tss for id

- lib/index.js
- lib/menu/app.js
- lib/ui/hud.jsx
- lib/ui/updatesDialog.jsx
- lib/update.js
- package-lock.json
- package.json
- styles/appc.less
Added update functionality, tried to replicate [vscode #80](https://github.com/appcelerator/vscode-appcelerator-titanium/pull/80) in atom.
Closes #157
> feat(updates): add update functionality

- dangerfile.js
- lib/appc.js
- package-lock.json
- package.json
- spec/appc-spec.js
- spec/utils-spec.js
Updates to the latest version of packages, which is just dev dependencies
| Package | Previous Version | New Version |
| ------- | --------------- | ----------- | 
| @atom/mocha-test-runner | 1.5.0 | 1.5.1  
| @commitlint/cli | 7.5.2 | 8.0.0  
| @commitlint/config-conventional | 7.5.0 | 8.0.0  
| @seadub/danger-plugin-junit | 0.0.2 | 0.1.1  
| commitizen | 3.0.7 | 3.1.1  
| danger | 7.0.19 | 8.0.0  
| eslint | 5.16.0 | 6.0.0  
| eslint-plugin-react | 7.12.4 | 7.14.1  
| etch | 0.12.8 | 0.14.0  
| husky | 1.3.1 | 2.5.0  
| lint-staged | 8.1.5 | 8.2.1  
| semver | 6.0.0 | 6.1.2  
| standard-version | 5.0.2 | 6.0.1
> chore(deps): update to latest dependency versions

- lib/index.js
- lib/touchBarManager.js
Triggered by [this tweet](https://twitter.com/YakupKalin/status/1033667394957455360) and currently untested because of missing touch-bar on this Mac. 
It does not error when opening Atom, so it might actually work. If so, we need to move this to the toolbar-code, where we have a callback when everything is loaded. we could then think of which commands make sense, like opening the controller/view/style?
> Support macOS Touch-Bar

- .travis.yml
See https://github.com/atom/ci/issues/94 for more info
We've had a slew of builds fails recently due to failing to extract the beta channel package, it seems this works on xenial so lets use that
> ci: move travis to using xenial to fix extract issues

- lib/index.js
Adding "Open related..." menu options to the context menu.
Current open tab will decide which options are visible.
Feature for: https://github.com/appcelerator/atom-appcelerator-titanium/issues/174
> Add "open related..." to context menu

- .eslintrc
- lib/appc.js
- lib/index.js
- lib/ui/toolbar.jsx
- lib/utils.js
- package.json
- spec/appc-spec.js
- spec/utils-spec.js
Prefer the fullname property of a certificate when displaying in the UI, as the name can be matching between the two this makes it easier to tell which is which, only show valid provisioning profiles, handle passing the correct certificate name to the SDK dependent on the projects version in the tiapp
Closes #183, kind of
> feat(ios): support generic apple certificates

- lib/providers/tiappAutoCompleteProvider.js
getPath returns undefined if the file is yet to be saved
Fixes #284
> fix(providers/tiapp): handle an open xml file that isn't on disk

- package-lock.json
- package.json
This is to fix an issue in the titaniumlib sdk extraction logic to ensure that symlinks are
preserved
> chore(deps): update titanium-editor-commons to 0.5.1

- lib/update.js
- lib/utils.js
- package-lock.json
- package.json
- spec/controllerAutoCompleteProvider-spec.js
- spec/styleAutoCompleteProvider-spec.js
- spec/viewAutoCompleteProvider-spec.js
Adds the node update and install functionality to atom, I have tried to keep it almost identical to how atom does it, the editor commons will need to be updated before this is merged
> feat(update): add node update and install functionality

- README.md
- lib/appc.js
- lib/index.js
- lib/ui/newProjectDialog.jsx
- lib/ui/toolbar.jsx
- lib/ui/updatesDialog.jsx
- lib/update.js
- lib/utils.js
- package-lock.json
- package.json
This PR introduces support for using the Ti and Alloy (OSS) tooling directly instead of the Appc tooling. This is enabled by a setting in the package settings, the default for now is to continue to use Appc tooling.
There are a couple commits that are general bug fixes that I needed to fix to be able to test fully or refactoring of unused/unnecessary code, namely:
* baa7b00a288fddc622f5cafe38d82ff56c37acd8 - fixes an issue when selecting a folder during project creation
* 8e73adb42ab38266c532b8993e3e9153f865dc7b - removes unused/unnecessary code
All other commits are pertinent to supporting the OSS tooling separated into the different areas to make reviewing easier, and will be squashed into one commit prior to merge.
> Support using OSS tooling

- CONTRIBUTING.md
- Jenkinsfile
- package-lock.json
- package.json
This PR moves us to using semantic-release, this is primarily because the current release mechanism has had issues the last few times when updating the development branch after release. So I figured rather than put in the work to correct the Jenkins workflow, we might as well just use something that does all the hard work for us and has an identical flow between Jenkins and a developers machine.
This is currently marked as a draft because as soon as it's merged Jenkins will (hopefully) fling out a new release. So, we only want to merge when we're ready
> build: move to using semantic-release for releasing

- package.json
As atom will trigger the postinstall script we want to make sure we dont error there, so if the
husky install fails exit with 0
> fix: exit 0 if husky errors

- lib/update.js
- package-lock.json
- package.json
Updates titanium-editor-commons to fix an oversight where the SDK wasn't selected after installing it. If any errors occur (for example appc ti sdk requires a login) then we'll show an error dialog on how to select it
> fix(updates): select Titanium SDK after installing it

- lib/update.js
- package-lock.json
- package.json
* Updates titanium-editor-commons to include appcelerator/titanium-editor-commons/pull/512
* Set an empty array on updates to ensure we don't error if the check fails
> fix: update editor-commons to fix issue when pulling latest npm version

- lib/index.js
- lib/project.js
- lib/ui/toolbar.jsx
The selected target (e.g. Simulator) could also be saved, but is a bit too complex right now, because it also related to the selected UUID's and profiles. Leaving that one open for now.
> Save environment across Atom launches

- lib/index.js
It's possible the toolbar has been uploaded between calling getInfo and setupTargets
Fixes #253
> fix: check for existence of toolbar before performing target setup 

- lib/providers/controllerAutoCompleteProvider.js
It's possible the toolbar has been uploaded between calling getInfo and setupTargets
Fixes #253
> fix: check for existence of toolbar before performing target setup

- lib/index.js
- lib/ui/toolbar.jsx
Adds a new dropdown when packaging to dist-appstore with the options Xcode or Folder, when Xcode is chosen we no longer pass `--output-dir` so the CLI will place the IPA into Xcode
Closes #85
> feat(ios): support outputting to xcode when performing a dist-appstore build

- lib/index.js
- lib/ui/toolbar.jsx
Adding a button to toggle dev-mode. Instead of trying to open the devtools right away (like #80) it will just attach `--debug-host localhost:8989` and you have to open the devtools yourself.
> Add Dev mode button

- .github/workflows/ci.yml
Action is failing for the beta channel. Since there aren't any new betas of Atom I've removed that and updated some versions.
Btw: https://github.com/pulsar-edit/pulsar might be the successor of Atom.
> fix(all) github action

- .github/workflows/release.yml
Missed this in the initial PR, release job [currently fails](https://github.com/tidev/atom-appcelerator-titanium/actions/runs/3236506162/jobs/5302406993) and this should fix it
> ci(release): install atom and apm first

- lib/ui/console.jsx
The console will automatically open some time when you open an old project. The `isHidden` state was automatically set to true, even if you don't use the console. 
It will still open when you press "play" or use the "toggle console"
Also setting the name to "Titanium console" instead of "Appcelerator Console".
> fix: keep console closed at startup

- .github/workflows/ci.yml
- package.json
- spec/controllerAutoCompleteProvider-spec.js
- spec/styleAutoCompleteProvider-spec.js
- spec/viewAutoCompleteProvider-spec.js
Part of #654
Uses the setup-pulsar action to test against pulsar, this isn't as full featured as the setup-atom one but handily the features it's missing (mainly testing against different versions) doesn't matter as the entire project is in beta.
There's still some iffy bits around apm/ppm usage but what's there right now works on all 3 platforms.
> ci: use pulsar action instead of atom

- .github/workflows/release.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
This moves over to using semantic-release-pulsar-config instead of @semantic-release/apm-config, the new package is basically the old one, just using `pulsar` to publish.
A new token will need to be configured in the secrets for this repo for automated publishing. However, I think for the first publish I will perform it locally just incase any issues arise
> chore: move to using semantic-release-pulsar

- lib/appc.js
- lib/index.js
- lib/keymap/app.js
- lib/keymap/module.js
- lib/menu/app.js
- lib/menu/module.js
- lib/ui/hud.jsx
- lib/ui/toolbar.jsx
The current commands have an `appc` prefix, this switches it to a `titanium` prefix, arguably a breaking change but I think we can get away with it
> fix(commands): rename command prefix to titanium

- lib/appc.js
- lib/ui/newProjectDialog.jsx
- spec/definitionsProvider-spec.js
Adding a checkbox to enable/disable Alloy projects when creating a new project:
_Note_: the change in `definitionsProvider-spec.js` was just a lint fix
> feat: alloy checkbox when creating a new project
