tidev/pulsar-titanium

lib/index.js, lib/providers/controllerAutoCompleteProvider.js, lib/providers/definitionsProvider.js, lib/providers/styleAutoCompleteProvider.js, lib/providers/tiappAutoCompleteProvider.js, lib/providers/viewAutoCompleteProvider.js
- [ATOM-33] Completion error shown in non-Titanium projects
- Click definitions ignored when Titanium project not open
- Fixed serialisation when Titanium project not open
=> Addresses errors when Titanium project not open

lib/ui/toolbar.js
=> linux compatibility

lib/appc.js, lib/index.js, lib/keymap/app.js, lib/menu/app.js, lib/ui/toolbar.js
Adding a `clean` button to the menu:
Not sure about the trash icon but didn't find any better in the octicons :)
=> Clean button

lib/appc.js, lib/index.js, lib/menu/app.js, lib/ui/loginDialog.jsx, styles/appc.less
* alphabetic menu order
* added a separator before "new project" (it's getting added via script so it is at the bottom of the menu)
* added `Appcelerator Login` to perform an `appc login` if needed
=> Appc Login menu, various optimizations

lib/ui/button.jsx, lib/ui/select.jsx, lib/ui/toolbar.jsx, package.json
Adding titles to the buttons and select fields
=> Add UI titles

.eslintrc, CONTRIBUTING.md, Jenkinsfile, dangerfile.js, lib/providers/viewAutoCompleteProvider.js, lib/ui/button.jsx, lib/ui/loginDialog.jsx, lib/ui/select.jsx, lib/ui/toolbar.jsx, package-lock.json, package.json, spec/.eslintrc, spec/appc-spec.js, spec/styleAutoCompleteProvider-spec.js, spec/test-runner.js, spec/utils-spec.js, spec/viewAutoCompleteProvider-spec.js
This moves us to:
* Using mocha and chai for tests in line with other projects
* Fixes up the eslint setup to lint jsx files
* Sets up danger
=> Fixup some linting and test misses, move to mocha and chai, setup danger,

lib/index.js, lib/ui/toolbar.jsx
Adds a config setting for hiding/showing the toolbar, when the toolbar is toggled we set that. When we open a project we also check that value and set the visibility of the toolbar to config setting
Closes #148
=> feat(toolbar): add config setting for showing toolbar, respect on open

Jenkinsfile, lib/providers/autoCompleteHelper.js, lib/providers/styleAutoCompleteProvider.js, lib/utils.js, package.json, spec/styleAutoCompleteProvider-spec.js
Steps to reproduce;
1. Open project
2. Open a Tss file
3. Add color or layout property
Fixes #152
=> fix(styleprovider): improved suggestions to include quotes for color and layout properties

lib/providers/autoCompleteHelper.js, spec/styleAutoCompleteProvider-spec.js, spec/viewAutoCompleteProvider-spec.js
This fix improves the ordering of suggestions and adds the deprecated label to properties
Fixes #143
=> fix(provider): improve ordering of suggestions

lib/appc.js, lib/ui/newProjectDialog.jsx, lib/utils.js, package-lock.json, package.json
We removed the option to add test module in the cli but we were still checking for it here blocking the
appc new.
Fixes #158
=> fix(app creation): fixed the app creation flow for newer sdks

lib/appc.js, lib/index.js, lib/ui/toolbar.jsx
Add user information and login icon to the toolbar and updated the check login to open the login dialog
if not logged in.
Fixes #159
=> feat: add user information and login icon to toolbar

lib/index.js
=> feat: show login dialog if login is required to run command

package-lock.json, package.json
Fixes an issue where sdks and modules were being extracted and executables were losing their permissions
=> chore(deps): update titanium-editor-commons to 0.4.0

lib/providers/controllerAutoCompleteProvider.js, spec/controllerAutoCompleteProvider-spec.js
Added completions for Ti namespace in controllers with methods and properties
fixes #171
=> feat(completion): add completions for Ti namespace in controllers

lib/providers/autoCompleteHelper.js, lib/providers/controllerAutoCompleteProvider.js, package-lock.json, package.json, spec/controllerAutoCompleteProvider-spec.js, spec/data/completions.json, spec/styleAutoCompleteProvider-spec.js, spec/viewAutoCompleteProvider-spec.js
Added alloy namespace to completions and updated to get version 2 of the generated completions.
Fixes #179
Please merge #177 first
=> feat(completions): added completions for Alloy namespace in controllers

lib/providers/controllerAutoCompleteProvider.js, lib/providers/styleAutoCompleteProvider.js, lib/providers/viewAutoCompleteProvider.js
Refactor code to maintain the same flow across all the different providers
Fixes #188
=> fix(completion): handle array being returned from getCompletions

lib/appc.js, lib/index.js, package.json
Started to add a `ti commands` option:
Still need to change some strings inside the package but building and cleaning work already.
=> Use ti commands

.github/workflows/ci.yml
So we can gate the tests running with a successful linting run
=> ci: run tests after linting

lib/index.js, lib/project.js, lib/ui/octicon.jsx, lib/ui/toolbar.jsx, package-lock.json, package.json
* Build information is now persisted between sessions
* Fixes open file dialog on keystore selection
* Updates the liveview icon to better distinguish states
* Updates editor-commons to fix an issue when the install fails due to requiring sudo
=> Release changes

lib/index.js, lib/touchBarManager.js
The electron API had changed so the usage was no longer correct and not rendering
=> fix(touchbar): adapt to new touchbar API

lib/ui/toolbar.jsx
=> feat(toolbar): add clean button to toolbar

lib/ui/console.jsx
=> feat(console): allow positioning console anywhere in the atom window 

CHANGELOG.md, README.md, package.json
replacing the repo and issue links in the Changelog, Readme and package.json
=> fix: links to repo and issues

lib/ui/octicon.jsx, lib/ui/toolbar.jsx, styles/appc.less
Make the Liveview icon dark if disabled so it will fit better
=> fix(all): liveview icon color

.github/workflows/ci.yml, .github/workflows/release.yml, package-lock.json, package.json
* update workflow
* update `titanium-editor-commons`
=> chore: update packages
